git:
  depth: 5
language: node_js
node_js:
  - 'stable'
deploy:
  provider: npm
  email: pedre87@gmail.com
  api_key:
    secure: AXStiz/hnzvL2srNV0VfZKlZFDirkSM4q7mGok+eX31rOCmpp0eWtIqrdf5aZ1AYZJ6CQK+mbLIawgyudDqI7H9x1toSbyTsMlRbLaz6rZQSfFZSsE5VEdp0glbSatiBpeAG7foB8Q+5xO3pp3NmR2G8OJcsjwsId+YwVcLiKdczjZfEOTZsZ30gQidPquo+Twi7T1RdQ5b95IgDzJOlPYBzCmMHRQoyLKpsODfDEe7Sad3d3EPqKKeWX7vZJTGgHh+l67UUKmilPT8lb438V4XEM7+gyyX4T5Zj5/EOXtnpNIYKuaCcXmbItZHUXfrAEThghzWcRiivPwnBRi0eZrJAvWXJzsQzYdht6mx4Y0PKTsHollZvVQueIbJDB1/JGhHTG9a0ecOdThTb36xJ4LdxozOmIvSRY9t7f+PohqZ7vW1/qT9nTy+ou3uh2T3X4UIQlQu6ui0y6Rx6Inn0b+snQudaCJkEQ5J1oCtVNUAIys04Lc5EuVB35ZqAbSwvLKA5+WOd6RkQcS+ZSUBgZZ6oIkOtcEGiuQF1weOFzMNQr9gDe+qAjgvPXEivMnixl8L7VLNtWTJ0zZyyysjk4rWXEuWAZdZFUwKkKkgmctLAl0IWtdYJ20XYMImgWraGXyAEN4wNPdDceAqiINCv7bbBG8BHhorbuCDzQeLg6A0=
  on:
    branch: master