git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: IerN/RTZ+nW+ytdypeoLKhcxoXqrv4Dqq71Yr1YSE5LSXNRB5b1ZdlQb0cAy2JwC9tScM6e6vhactbruKI8HPAifE2PQlnqUPMp3yQN5W1Q2TzNZJZUzDziidAdRnXc2pPGwg7wpkg3+YCoN+yMdojht/O15Vl548uELtFWxnbs3ElJ0afVSA25H4UqbXU2Py13rNpWXhw2ovVnQwtnnEOE2qu+pUMbplh4rBnWOJaupFxclP//VgFnS0WO4n8ZNaPWPh1AASYj/hYC35xlxX6VKQ0ph/xhe58RzRUe8EaI/qUWGvRa/x9CrAvklJUlV0uoq7GhdNujq7in6pkSdtLfOJgtyekvgmZyDsRExiRpjuxR2SCrHu467RAJHpIA/H4ut28q0pv0tk0DR9j5WrrSFERUA+txlnaE7bUGw51omHdu+DSD/NF4Mcicc8FeUyVjZ7Rs93BHQPxQaDcMkstIjfsgdShKXHWtiAu2Cp8+6Blq/NRY4Csrq7nyjcY6UGd1t3vaPG3YLNVPrlbQ28VKtkgz/EUyFcm4vXtulxMDEsKzGVEgjOq5aUp94G52o2xLV56vD8d3++iHv/biujx0/Ck3YLUvYe29TERc7wZgWApapOpH8n3oL5rmYCjfCEYaxQsmIftUFmjtExVOGpGHSQF3PyfcQ+qOVDTjMDCc=
script:
- nohup yarn test
