git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: e4wRr3OeYhIFBuz9tRsu57ZXY+ym8nL+eaAxdBtpDtT4kFb5aWPclP21zMcO4DwPLRI9QIf+1g/WTZfhskEYEgVq0OtvZtCAQi7Zi66CNETTExuzZNeqVXjOv6lesJ62Axm7+hL9ig/mcQhkbTDcCsEwNP/RTMDXYmDI+2oNzktsdbeNXF9kbEuRgzfr3PLNezVyARcaXtVSVvcsGfYSfn00qIbZGBGUff1N1ob/p2sJb+IuKfHH66Nizdu6Q7C0n0Aau1Iiv241QNcxtD272UZvAxLH7hTngATIjYRW6ctc85TLjmPKLvX3ol7/fVJvtqLMtF9wbv/P15ujx1guF/4u8TWIjgTamJdo3XjVy+6omR1M8rtHTkUg8Rt29IKrxqqm+ZxxfE0XfCQ1pW0Sx2OMS/VN/QCMD8q/vpVD815NPnC+9szWrhlkKeH6R0HECYbnLym+ntWdXmqId+Y0baTNZ1tY7eLWUIf1LyqPR8vCObcvCD6OnqkpAmskqqWTOjL2DEu+QknwEo0N2ORMyAUJSLGWUoQkbNcdXRTN9tizwydflXG2RhcAVNs340BwT7flPpUIMasuAUFrzCe6VrbY1LP7Rmkc88FaRfYOhKvwdnvyABUMPgG7kEJYceRedM7YEunELJPR/wgDpu2L0H5kb4G88N2uoo3SX5kJw7o=
script:
- nohup yarn test
